# NumPY


    NumPy yra tiesinės algebros biblioteka. Jos pagrindu sukurtos beveik visos su duomenų mokslu susijusios bibliotekos, tokios kaip Pandas ir kt. Numpy yra itin greita, nes yra susieta ryšiais(bindings) su C kalba parašytais moduliais.

    Standartiškai įsidiegia pip install numpy, jeigu naudojate Anaconda - conda install numpy
    Dažniausiai naudojamas NumPy ingredientas - NumPy masyvai. Jie būna dviejų tipų - vektoriai ir matricos.

    Prieš pradedant darbą su NumPy, reikia jį importuoti.


In [2]:
import numpy as np

In [5]:
# tarkime, turime paprastą Python list'ą:
sarasas = [5, 1, 3, 7, 6]

# paverskime jį į NumPy array:
vektorius = np.array(sarasas)
vektorius

#gauname 1 lygio NumPy masyvą (vektorių).

array([5, 1, 3, 7, 6])

In [7]:
# Jeigu norime matricos, turime sukurti keletą masyvų masyve:
sarasai = [
    [4, 5, 6],
    [1, 2, 3],
    [7, 8, 9]
]
matrica = np.matrix(sarasai)
matrica

matrix([[4, 5, 6],
        [1, 2, 3],
        [7, 8, 9]])

In [9]:
# NumPy turi ir integruotus, paprastus būdus susikurti masyvą. Skliausteliuose reikia įrašyti start, stop ir step(nebūtina) reikšmes:
np.arange(0, 78, 7)

array([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77])

In [11]:
# jeigu reikia vektoriaus iš nulių:
print(np.zeros(7))

[0. 0. 0. 0. 0. 0. 0.]


In [12]:
# jeigu matricos iš nulių:
print(np.zeros((7, 7)))

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [141]:
# Analogiškai veikia np.ones metodas.
vienetai = np.ones(10)
vienetai

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
# Dar viena naudinga funkcija - linspace. 
# Ji grąžina masyvą, su lygiais intervalais išdėliotomis reikšmėmis. 
# Reikia nurodyti start, stop ir intervalo reikšmes:
print(np.linspace(0, 20, 5))

[ 0.  5. 10. 15. 20.]


In [17]:
# Jeigu prireikė vienetinės matricos:

print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [21]:
vienetine = np.eye(7, dtype=int)
vienetine[3, 4] = 5
print(vienetine)

[[1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 1 5 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1]]


# Random array/matricos kūrimas

In [22]:
# Pirmas metodas susikurti random array - np.random.rand(). 
# Jo pagalba galime susikurti masyvą su atsitiktinėm reikšmėm nuo 0 iki 1 ("uniform" distribution)

np.random.rand(10)

array([0.26926243, 0.82342427, 0.417445  , 0.92755919, 0.9457926 ,
       0.12578951, 0.77656925, 0.60357571, 0.02090455, 0.02528824])

In [24]:
# jeigu norime ne vektoriaus, o matricos:
print(np.random.rand(5, 5))


[[0.610774   0.75044776 0.86639586 0.9749449  0.38743193]
 [0.1380015  0.87279309 0.12134232 0.59739382 0.72627612]
 [0.16084439 0.81769508 0.42539956 0.52347655 0.55928316]
 [0.61376998 0.94831624 0.48352774 0.11583489 0.85507059]
 [0.57084262 0.7784828  0.95656195 0.24845184 0.98853037]]


In [25]:
# np.random.randn() sugeneruos reikšmes iš “standard normal” distribution (standartinis normalusis skirstinys)
# negatyvios reiksmes
print(np.random.randn(3, 3))


[[ 0.01031619 -0.75150074 -1.42093813]
 [ 0.92820934  0.99033711  1.21285585]
 [-0.98969912  0.0825615  -0.16899248]]


In [37]:
# np.random.randint() sugeneruoja atsitiktines integer reikšmes. 
# Parametruose reikia nurodyti, žemiausią, aukščiausią (neįskaitant) reikšmes ir norimą kiekį reikšmių.

print(np.random.randint(-10, 11, 77))
# iki yra neimtinai, tai jei nori iki 10, tai rasai 11, nes 10 nebepaima, jei rasai iki 10. 

[ -9  -7  -9   9  -1  -3   6   3  -7  -8   1  -8  10   0   1  -2   9  -7
   9   8   1  -9  -2  -3 -10  -6  10 -10  -8  -9  -7  -3   8  -8   4   5
  -2  -8  -8  -4  -2  -7   3   4   7   7  -7  -5   1  -4  -2   8  -7  -7
   9   2   4   3  -1  -8  -9  -9   4   7   3   0  -9   2  -1   2   2  -6
  -3 -10   1   2   3]


# Masyvų pertvarkymas

reshape() metodas leidžia mums performuoti turimą masyvą į kitą formą:


In [47]:
# perdarem masyva i 7x7 matrica
# paskutinis skaicius skliaustuose, siuo atveju 40, turi sutapti su pertvarkyto masyvo skliaustuose skaiciu daugyba 5*8, kitaip mes klaida
masyvas = np.random.randint(-99, 100, 40)
pertvarkyta = masyvas.reshape(5, 8)
print(pertvarkyta)



[[-98  36  43  71   6 -34 -80 -40]
 [-20  74 -23 -67   1 -29 -97  18]
 [  5  33 -95 -17   3  65 -59  -2]
 [  1  42  84 -10   9  95  44 -35]
 [ 83 -68  35  57 -37   0  -3  74]]


# Naudingi Metodai

In [48]:
# max() ir .min() metodai ištraukia maksimalią ir minimalią reikšmes iš masyvo:
print(pertvarkyta.min())
print(pertvarkyta.max())

-98
95


In [49]:
# argmax() ir argmin() nurodo mums maksimalios ir minimalios reikšmių indeksą:
print(pertvarkyta.argmin())
print(pertvarkyta.argmax())

0
29


In [51]:
# .shape nurodo, kokią formą turi mūsų masyvas:
print(pertvarkyta.shape)

# .dtype nurodo, koks duomenų tipas yra mūsų masyve:
print(pertvarkyta.dtype)

# cia yra ne funkcijos, o savybes


(5, 8)
int32


# Indeksacija ir reikšmių traukimas

In [54]:
# reikšmę iš vektoriaus traukiame taip pat kaip ir iš Python sąrašo:
masyvas[5]

-34

In [55]:
# galime naudoti slices:
masyvas[3:13]

array([ 71,   6, -34, -80, -40, -20,  74, -23, -67,   1])

In [59]:
# galime pasirinktam rėžiui suteikti kokią nors savo reikšmę (Broadcasting):
masyvas[::4] = 44
masyvas[7] = 77
masyvas[21] = -42

In [62]:
masyvas.reshape(4, 10) # kas 4 reiksmei priskirta 44

array([[ 44,  36,  43,  71,  44, -34, -80,  77,  44,  74],
       [-23, -67,  44, -29, -97,  18,  44,  33, -95, -17],
       [ 44, -42, -59,  -2,  44,  42,  84, -10,  44,  95],
       [ 44, -35,  44, -68,  35,  57,  44,   0,  -3,  74]])

In [64]:
pertvarkyta[0, 0]

44

# Reikšmių traukimas iš matricos

In [66]:
pertvarkyta[1:4, 5:8]

array([[-29, -97,  18],
       [-42, -59,  -2],
       [ 95,  44, -35]])

In [67]:
masyvas = np.random.randint(0, 100, 100)
matrica = masyvas.reshape(10, 10)
matrica

array([[ 8, 67, 14, 77, 43, 78, 85,  0, 90, 47],
       [47, 25,  2, 69, 43, 36, 23, 32, 41, 57],
       [31, 36, 90, 80, 13, 18, 85, 41, 83, 86],
       [94, 91, 50, 62, 98,  7, 25, 57, 18, 99],
       [83, 46, 32, 46, 37, 50, 53,  1, 14, 97],
       [75, 79,  7, 30, 93, 53, 66, 17, 71, 77],
       [83, 39, 67, 81, 86, 25, 90, 68, 83, 62],
       [91, 32, 91, 20, 43,  6,  8, 57, 96, 27],
       [51, 92,  6, 63, 10, 99, 35, 61, 79, 97],
       [58, 49, 47, 54, 61, 33, 93, 20, 82, 34]])

In [68]:
# laužtiniuose skliausteliuose pirmiau nurodome eilutę, paskui tos eilutės nario indeksą.
# taip pat galime naudoti rėžius:
matrica[::2, ::2]

array([[ 8, 14, 43, 85, 90],
       [31, 90, 13, 85, 83],
       [83, 32, 37, 53, 14],
       [83, 67, 86, 90, 83],
       [51,  6, 10, 35, 79]])

In [69]:
matrica[-2::-2, -2::-2]

array([[79, 35, 10,  6, 51],
       [83, 90, 86, 67, 83],
       [14, 53, 37, 32, 83],
       [83, 85, 13, 90, 31],
       [90, 85, 43, 14,  8]])

In [70]:
# jei norim pirmo stulpelio
matrica[:, :1]

array([[ 8],
       [47],
       [31],
       [94],
       [83],
       [75],
       [83],
       [91],
       [51],
       [58]])

In [71]:
# jei norim antro stulpelio
matrica[:, 1:2]

array([[67],
       [25],
       [36],
       [91],
       [46],
       [79],
       [39],
       [32],
       [92],
       [49]])

In [72]:
# jei norim dvieju stulpeliu
matrica[:, 0:2]

array([[ 8, 67],
       [47, 25],
       [31, 36],
       [94, 91],
       [83, 46],
       [75, 79],
       [83, 39],
       [91, 32],
       [51, 92],
       [58, 49]])

# Reikšmių traukimas pagal sąlygą

In [119]:
# Tarkime, turime masyvą:
masyvas

array([30, 67, 30, 77, 43, 78, 85, 30, 90, 47, 47, 30, 30, 69, 43, 36, 30,
       32, 41, 57, 31, 36, 90, 80, 30, 30, 85, 41, 83, 86, 99, 99, 99, 99,
       99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99, 99, 99, 99, 99, 99, 99, 83, 39, 67, 81, 86, 30, 90, 68,
       83, 62, 91, 32, 91, 30, 43, 30, 30, 57, 96, 30, 51, 92, 30, 63, 30,
       99, 35, 61, 79, 97, 58, 49, 47, 54, 61, 33, 93, 30, 82, 34])

In [120]:
masyvas > 30

array([False,  True, False,  True,  True,  True,  True, False,  True,
        True,  True, False, False,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True, False,  True,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True])

In [121]:
# norime reiksmiu daugiau uz 30
masyvas[masyvas > 30]

array([67, 77, 43, 78, 85, 90, 47, 47, 69, 43, 36, 32, 41, 57, 31, 36, 90,
       80, 85, 41, 83, 86, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 83, 39, 67, 81, 86, 90, 68, 83, 62, 91, 32, 91, 43, 57, 96, 51,
       92, 63, 99, 35, 61, 79, 97, 58, 49, 47, 54, 61, 33, 93, 82, 34])

In [122]:
iki_30 = masyvas < 30
print(iki_30)

[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False]


In [123]:
masyvas[iki_30]

array([], dtype=int32)

In [124]:
masyvas[iki_30] = 30
masyvas

array([30, 67, 30, 77, 43, 78, 85, 30, 90, 47, 47, 30, 30, 69, 43, 36, 30,
       32, 41, 57, 31, 36, 90, 80, 30, 30, 85, 41, 83, 86, 99, 99, 99, 99,
       99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99, 99, 99, 99, 99, 99, 99, 83, 39, 67, 81, 86, 30, 90, 68,
       83, 62, 91, 32, 91, 30, 43, 30, 30, 57, 96, 30, 51, 92, 30, 63, 30,
       99, 35, 61, 79, 97, 58, 49, 47, 54, 61, 33, 93, 30, 82, 34])

# Numpy elgsenos ypatumai

In [125]:
naujas = np.random.randint(0, 100, 20)
naujas[naujas > 50] = np.random.randint(0, 100)
naujas

array([ 0, 22,  0,  3,  1,  0, 22, 26,  0, 24,  0, 49,  0,  0, 20, 30, 49,
       20,  0,  0])

In [127]:
# turime random masyvą iš integer reikšmių. Susikurkime jo atraižą:
# ispjova
masyvas = np.random.randint(0, 100, 100)
kopija = masyvas.copy()
ispjova = kopija[30:60]
ispjova[:] = 99
print(masyvas)
print(kopija)
print(ispjova)


[56 19 60 11 47 81 64 60 27 94 39 18 62 10 80 31 17 12 90 82 72 72 92 70
 87 37 46 36 76 94 23 28 53 50 47 12 41 42 30  3 12 64 11 59 53 53 31 54
 20 62 24 53 37  3  9  2 27  7 82 88 98 48 55 73 60 43 65 85 80 65 73 27
 97 25 20 12 71 93 71 72 75 15 70 46 94 11 20 93 20  4 82 10 67 11 80 78
 39 85 67 78]
[56 19 60 11 47 81 64 60 27 94 39 18 62 10 80 31 17 12 90 82 72 72 92 70
 87 37 46 36 76 94 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99
 99 99 99 99 99 99 99 99 99 99 99 99 98 48 55 73 60 43 65 85 80 65 73 27
 97 25 20 12 71 93 71 72 75 15 70 46 94 11 20 93 20  4 82 10 67 11 80 78
 39 85 67 78]
[99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99
 99 99 99 99 99 99]


Paprastai kuriant kintamąjį, užkulisiuose padaroma kopija šaltinio, iš kurio jis gaminamas (šiuo atveju pvz). Iš tos kopijos formuojamas naujas kintamasis. Tačiau NumPy atveju pakeitimai vykdomi originale, ir mums rodoma tik modifikuota to originalo dalis. NumPy pritaikytas darbui su milžiniškais kiekiais duomenų. Daryti laikinas jų kopijas atmintyje yra neefektyvu, ir nestabilu. Todėl, kai norime išsaugoti originalą, turime nurodyti, kad norėsime pasidaryti kopiją:

In [128]:
masyvas.copy() == masyvas

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [129]:
tarpinis = masyvas[masyvas >= 30]
tarpinis[tarpinis < 60]

array([56, 47, 39, 31, 37, 46, 36, 53, 50, 47, 41, 42, 30, 59, 53, 53, 31,
       54, 53, 37, 48, 55, 43, 46, 39])

# Matematinės operacijos ir funkcijos

su NumPy arrays galima atlikti paprastus aritmetinius veiksmus:

In [130]:
vektorius = np.arange(1, 11, 1)
vektorius

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [131]:
vektorius + vektorius

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [132]:
vektorius - vektorius

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [133]:
vektorius ** vektorius

array([         1,          4,         27,        256,       3125,
            46656,     823543,   16777216,  387420489, 1410065408])

In [134]:
vektorius ** 3

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [135]:
vektorius ** 3 / vektorius

array([  1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100.])

In [136]:
vektorius / 0

C:\Users\ingri\AppData\Local\Temp\ipykernel_24768\17242066.py:1: RuntimeWarning: divide by zero encountered in divide
  vektorius / 0


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [137]:
# atkreipkite dėmesį, atlikus dalybą iš 0 gausime begalybes arba nan - not a number. Taip pat galime atlikti veiksmus ir su skaičiais:
(vektorius + 100) / 10

array([10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9, 11. ])

In [138]:
# Numpy aplinkoje taip pat galime taikyti įvairias trigonometrines funkcijas ir tt.
np.sin(vektorius)


array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [139]:
np.tan(vektorius)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501,
       -0.29100619,  0.87144798, -6.79971146, -0.45231566,  0.64836083])

In [140]:
np.log(vektorius)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])