# Užduotys
**Atkreipkite dėmesį, kad, jeigu neteisingai įvesite atsakymą, Out reikšmė irgi pasikeis**

In [3]:
import numpy as np

1. Sukurkite vektorių su skaičiais nuo 1 iki 9

In [5]:
vektorius = np.arange(1, 10)
vektorius

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

2\. Sukurkite vektorių iš 10 nulių

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3\. Sukurkite vektorių iš 10 vienetų

In [9]:
vienetai = np.ones(10)
vienetai

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

4\. Sukurkite vektorių iš 10 ketvertų

In [23]:
ketvertai = np.ones(10) * 4
ketvertai

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

5\. Sukurkite vektorių iš lyginių skaičių nuo 0 iki 100

In [24]:
vektorius_lyginiai = np.arange(0, 101, 2)
vektorius_lyginiai

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

6\. Sukurkite matricą iš 25 narių, pradedant 1, baigiant 25. Priskirkite ją kintamąjam.

In [31]:
matrica = np.arange(1, 26).reshape(5, 5)
matrica


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

7\. Iš matricos ištraukite skaičių 12

In [33]:
matrica[2, 1]

12

8\. Iš matricos ištraukite paskutinę eilutę.

In [34]:
matrica[4, :]

array([21, 22, 23, 24, 25])

In [35]:
matrica[-1]

array([21, 22, 23, 24, 25])

9\. Iš matricos ištraukite submatricą

1, 2, 3  
6, 7, 8  
11,12,13

In [38]:
# matrica[nuo kurios eilutes imsim; iki kurios eilutes imsim, nuo kurio stulpelio imsim: iki kurio stulpelio imsim
matrica[:3, :3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

10\. Iš matricos ištraukite submatricą

7, 8, 9, 10  
12, 13, 14, 15  
17, 18, 19, 20

In [49]:
matrica[1:4, 1:]

array([[ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20]])

11\. Iš matricos ištraukite submatricą

16, 17, 18  
21, 22, 23

In [65]:
matrica[3:, :3]

array([[16, 17, 18],
       [21, 22, 23]])

12\. Sukurkite vektorių iš 20 atsitiktinių reikšmių nuo 0 iki 1. Priskirkite kintamąjam.

In [67]:
atsitiktiniai = np.random.rand(20)
atsitiktiniai

array([0.35872681, 0.02860466, 0.08535121, 0.28473282, 0.61451257,
       0.15440166, 0.3505741 , 0.32803613, 0.43504119, 0.91407956,
       0.18791476, 0.04886212, 0.21177052, 0.26125057, 0.02302616,
       0.76810929, 0.23135489, 0.44260608, 0.42293685, 0.4053009 ])

array([0.8583063 , 0.7839858 , 0.15307399, 0.74393181, 0.13574434,
       0.36289168, 0.13960192, 0.18715374, 0.29947662, 0.7245185 ,
       0.06837904, 0.44806807, 0.31655348, 0.21103823, 0.6815801 ,
       0.81323892, 0.48069123, 0.57937349, 0.72240019, 0.65220459])

13\. Suraskite didžiausią reikšmę masyve ir jos indeksą.

In [68]:
atsitiktiniai.max()

0.9140795643190817

In [71]:
atsitiktiniai.argmax()

9

0.8583063020360838

0

14\. Suraskite mažiausią reikšmę ir jos indeksą

In [72]:
atsitiktiniai.min()

0.023026160526430917

In [73]:
atsitiktiniai.argmin()

14

0.06837904455958688

10

15\. Atspausdinkite šio vektoriaus duomenų tipą

In [75]:
atsitiktiniai.dtype

dtype('float64')

dtype('float64')

16\. Sukurkite vektorių iš integer reikšmių nuo 1 iki 100. Priskirkite kintamąjam. Iš jo ištraukite visus skaičius, didesnius už 90

In [79]:
simtas = np.arange(1, 101)
simtas

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [80]:
simtas[simtas > 90]

array([ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

array([ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

17\. Ištraukite iš vektoriaus visus skaičiaus 7 kartotinius

In [81]:
simtas[simtas % 7 == 0]

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98])

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98])

18\. Sukurkite tokią matricą:

In [55]:
# array([[0.025, 0.05 , 0.075, 0.1  , 0.125, 0.15 , 0.175, 0.2  ],
#        [0.225, 0.25 , 0.275, 0.3  , 0.325, 0.35 , 0.375, 0.4  ],
#        [0.425, 0.45 , 0.475, 0.5  , 0.525, 0.55 , 0.575, 0.6  ],
#        [0.625, 0.65 , 0.675, 0.7  , 0.725, 0.75 , 0.775, 0.8  ],
#        [0.825, 0.85 , 0.875, 0.9  , 0.925, 0.95 , 0.975, 1.   ]])


In [84]:
flauto_matrica = np.arange(0.025, 1.025, 0.025).reshape(5,8)
flauto_matrica

array([[0.025, 0.05 , 0.075, 0.1  , 0.125, 0.15 , 0.175, 0.2  ],
       [0.225, 0.25 , 0.275, 0.3  , 0.325, 0.35 , 0.375, 0.4  ],
       [0.425, 0.45 , 0.475, 0.5  , 0.525, 0.55 , 0.575, 0.6  ],
       [0.625, 0.65 , 0.675, 0.7  , 0.725, 0.75 , 0.775, 0.8  ],
       [0.825, 0.85 , 0.875, 0.9  , 0.925, 0.95 , 0.975, 1.   ]])

In [85]:
np.linspace(0.025,1,40).reshape(5,8)

array([[0.025, 0.05 , 0.075, 0.1  , 0.125, 0.15 , 0.175, 0.2  ],
       [0.225, 0.25 , 0.275, 0.3  , 0.325, 0.35 , 0.375, 0.4  ],
       [0.425, 0.45 , 0.475, 0.5  , 0.525, 0.55 , 0.575, 0.6  ],
       [0.625, 0.65 , 0.675, 0.7  , 0.725, 0.75 , 0.775, 0.8  ],
       [0.825, 0.85 , 0.875, 0.9  , 0.925, 0.95 , 0.975, 1.   ]])

19\. sukurkite tokia matrica (sveiki sk. nuo 2 iki 1000, iš kurių traukiasi sveika šaknis):

In [74]:
# array([[  4,   9,  16,  25,  36],
#        [ 49,  64,  81, 100, 121],
#        [144, 169, 196, 225, 256],
#        [289, 324, 361, 400, 441],
#        [484, 529, 576, 625, 676],
#        [729, 784, 841, 900, 961]])

In [119]:
matricaa = np.arange(2, 32)**2
rezultas = matricaa.reshape(6, 5)
rezultas

array([[  4,   9,  16,  25,  36],
       [ 49,  64,  81, 100, 121],
       [144, 169, 196, 225, 256],
       [289, 324, 361, 400, 441],
       [484, 529, 576, 625, 676],
       [729, 784, 841, 900, 961]])

In [94]:
matricaaa = np.arange(2, 1000)
res = matricaaa[(matricaaa ** 0.5) % 1 == 0].reshape(6,5)
res
# kas tas ** 0.5 -> čia šaknies veiksmas taip iš kitos pusės aprašomas - kvadratinę šaknį galima pakeisti skaičių pakėlus kvadratu iš vienos antrosios,
#  kubinę šaknį galima pakeisti pakeliant kvadratu iš vienos trečiosios ir t.t.
# 4 pakelta kvadratu iš vienos antrosios bus 2, kas atitinka kvadratine sakni
# tikrina liekana dalybos is vieneto, nes reikalinga logine israiska, kad pagal ja atfiltruoti matricos narius

array([[  4,   9,  16,  25,  36],
       [ 49,  64,  81, 100, 121],
       [144, 169, 196, 225, 256],
       [289, 324, 361, 400, 441],
       [484, 529, 576, 625, 676],
       [729, 784, 841, 900, 961]])

20\. **(BONUS)**
* Sukurkite vektorių iš sveikų sk. nuo 1 iki 100. Priskirkite kintamąjam.
* Sukurkite Python funkciją, kuri tikrina ar parametruose įvestas sk. yra pirminis. Jeigu pirminis, grąžina True, jei ne, False.
* NumPy nevisada supranta įprastą Python kodą su range'ais ir list'ais, todėl sukurtą funkciją teks vektorizuoti taip : **nauja_funkcija = np.vectorize(jūsų_funkcija)**  .
* Kadangi sąlygos reikšmių traukimui yra *bool* reikšmės, pabandykite vietoje sąlygos įdėti savo vektorizuotą funkciją, ir taip išrinkti pirminius skaičius iš savo vektoriaus
.

In [96]:
vektorius_sveiki_sk = np.arange(2, 101)
vektorius_sveiki_sk

array([  2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
        54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
        67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
        80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
        93,  94,  95,  96,  97,  98,  99, 100])

In [123]:
def pirminis(skaicius):
    for i in range(2, skaicius):
        if skaicius % i == 0:
            return False
    return True

In [124]:
ar_pirminis = np.vectorize(pirminis)

In [125]:
vektorius_sveiki_sk[ar_pirminis(vektorius_sveiki_sk)]

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
       61, 67, 71, 73, 79, 83, 89, 97])